version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.17 # Specify the Node.js version
    steps:
      - checkout
      - run: npm install
      - run: npm test # Replace with your test command
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
